# SVD Example

In [2]:
# Singular Value Decomposition Example

import numpy as np

# example taken from Video Tutorials - All in One
# https://www.youtube.com/watch?v=P5mlg91as1c
a = np.array([[1, 1, 1, 0, 0],
              [3, 3, 3, 0, 0],
              [4, 4, 4, 0, 0],
              [5, 5, 5, 0, 0],
              [0, 2, 0, 4, 4],
              [0, 0, 0, 5, 5],
              [0, 1, 0, 2, 2]])

# set numpy printing options
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)

# Full SVD is taught more often. Here is a good explination of the different
# http://www.cs.cornell.edu/Courses/cs322/2008sp/stuff/TrefethenBau_Lec4_SVD.pdf
print ("--- FULL ---")
U, s, VT = np.linalg.svd(a, full_matrices=True)

print ("U:\n {}".format(U))
print ("s:\n {}".format(s))
print ("VT:\n {}".format(VT))

# the reduced or trucated SVD operation can save time by ignoring all the
# extremly small or exactly zero values. A good blog post explaing the benefits
# can be found here:
# http://blog.explainmydata.com/2016/01/how-much-faster-is-truncated-svd.html
print ("--- REDUCED ---")

U, s, VT = np.linalg.svd(a, full_matrices=False)

print ("U:\n {}".format(U))
print ("s:\n {}".format(s))
print ("VT:\n {}".format(VT))

--- FULL ---
U:
 [[-0.138  0.024 -0.011 -0.56   0.376  0.7    0.188]
 [-0.413  0.071 -0.032 -0.206 -0.756  0.258 -0.378]
 [-0.55   0.094 -0.043  0.725  0.185  0.344  0.092]
 [-0.688  0.118 -0.054 -0.344  0.231 -0.57   0.115]
 [-0.153 -0.591  0.654 -0.     0.2    0.    -0.4  ]
 [-0.072 -0.731 -0.678  0.     0.     0.     0.   ]
 [-0.076 -0.296  0.327 -0.    -0.4    0.     0.8  ]]
s:
 [ 12.481   9.509   1.346   0.      0.   ]
VT:
 [[-0.562 -0.593 -0.562 -0.09  -0.09 ]
 [ 0.127 -0.029  0.127 -0.695 -0.695]
 [-0.41   0.805 -0.41  -0.091 -0.091]
 [ 0.707 -0.    -0.707 -0.     0.   ]
 [ 0.    -0.     0.    -0.707  0.707]]
--- REDUCED ---
U:
 [[-0.138  0.024 -0.011 -0.56   0.376]
 [-0.413  0.071 -0.032 -0.206 -0.756]
 [-0.55   0.094 -0.043  0.725  0.185]
 [-0.688  0.118 -0.054 -0.344  0.231]
 [-0.153 -0.591  0.654 -0.     0.2  ]
 [-0.072 -0.731 -0.678  0.     0.   ]
 [-0.076 -0.296  0.327 -0.    -0.4  ]]
s:
 [ 12.481   9.509   1.346   0.      0.   ]
VT:
 [[-0.562 -0.593 -0.562 -0.09  -0.09 ]


In [3]:
U*s*VT

ValueError: operands could not be broadcast together with shapes (7,5) (5,5) 

In [4]:
s*VT

array([[-7.018, -5.637, -0.757, -0.   , -0.   ],
       [ 1.581, -0.274,  0.17 , -0.   , -0.   ],
       [-5.113,  7.652, -0.551, -0.   , -0.   ],
       [ 8.825, -0.   , -0.951, -0.   ,  0.   ],
       [ 0.   , -0.   ,  0.   , -0.   ,  0.   ]])

In [6]:
R=s*VT
R*U

ValueError: operands could not be broadcast together with shapes (5,5) (7,5) 